### ISSUE TITLE
Setting the env to sandbox in basic integration mode breaks popup

### ISSUE THREAD

**Issue by michael5r** [paypal/paypal-checkout#146]
In your basic integration demo (demo/button.htm), if you switch the env to 'sandbox' and click the checkout button, the popup will keep spinning forever - checking the console shows a 400 bad request on the call to sandbox.paypal.com/v1/oauth2/token and a "Unexpected end of JSON input" syntax error. This was working just fine about a week ago?

**Comment by bluepnume** [comment]
This is probably due to one of two things:

1. PayPal sandbox apis can be a little unreliable. We're actively working on improving this
2. Sometimes the request can error out if the header size is too large. Usually this is caused by too many cookies being sent. Can you try clearing cookies for .paypal.com and trying once more?

Thanks

**Comment by michael5r** [comment]
It's a christmas miracle! Wiping all cookies for paypal solved the issue - thanks!

**Comment by bluepnume** [comment]
It's a festivus miracle!

A few people have hit this problem, so I'll keep this open and try to track down which layer is rejecting these requests. Maybe we can bump the header size limit or at least add a meaningful error code.

**Comment by bluepnume** [comment]
Added https://github.com/paypal/paypal-checkout/issues/156 to track.
