### ISSUE TITLE
(gulp): Revise the gulp tasks

### ISSUE THREAD

**Issue by trainerbill** [paypal/paypal-checkout#231]
I can look into these, just putting some thoughts down.

After working a bit with the build process, it is very slow and redundant in some places.  Things we need to look into:

1.  Why is Webpack taking almost 3 minutes in karma task.  Pretty sure it has something to do with the babel loader.

![image](https://cloud.githubusercontent.com/assets/3578259/23667600/05bfc5c4-0324-11e7-9f24-30dbded2e06c.png)

2.  How can we do a simple build and place the file somewhere to test?  I ran gulp webpack/build and got the files but if I put them in an application it was erroring because the it was sending the new minor version to the iframe.  I had to do a search and replace on the file to change say 4.0.47 back to 4.0.46.  I think it would be best to just use npm version instead of all those functions in webpack config.  I think you just roll with the current version in package.json and then when npm version patch is executed then the version will bump in package.json and you have one webpack config that read the version from there.

3.  typeflow is slooowww.

Need speed improvements about everywhere.

**Comment by bluepnume** [comment]
> Why is Webpack taking almost 3 minutes in karma task. Pretty sure it has something to do with the babel loader.

That's my guess too. I'd be extremely happy if you find any way to speed this up.

> How can we do a simple build and place the file somewhere to test? I ran gulp webpack/build and got the files but if I put them in an application it was erroring because the it was sending the new minor version to the iframe.

The best way is:

1. Use `checkout.js` not `checkout.x.y.z.js`
2. Add `data-paypal-checkout` in the script tag like `<script src="./checkout.js" data-paypal-checkout></script>`

Then in the child, it will pull in `checkout.js` from paypalobjects rather than trying to get a specific version.

The reason it tries to get a specific version is so if people save checkout.js to their own web-server, the version will always match up in the child.

> typeflow is slooowww.

That's weird. I normally run it with just `flow` unless I'm doing a full build, and it's pretty snappy. 

```bash
LM-SJN-21009767:paypal-checkout dbrain$ time flow
No errors!

real	0m0.119s
user	0m0.058s
sys	0m0.022s
```
