### ISSUE TITLE
Return name/shipping from Hermes to onAuthorize callback

### ISSUE THREAD

**Issue by trainerbill** [paypal/paypal-checkout#275]
90% of merchants will only use the data to make the api call to get the name/address/phone/email of the user in order to prepopulate their form fields.  Would be more efficient if we did that for them.  This is what Braintree does as well.

Just a thought.

**Comment by bluepnume** [comment]
Things to consider:

- The data changes after `execute()` so people may execute and then use `data.payment` and get stale data they weren't expecting
- The data isn't typically used by advanced integrations, so it's a wasteful call for those guys
- Same for basic integrations with immediate execute
- Would mean two ways of doing things rather than one

So want to think about this a little...

**Comment by bluepnume** [comment]
Going to close this unless any demand comes up for it.
