### ISSUE TITLE
Old UI loading into the Popup window?

### ISSUE THREAD

**Issue by yabdab** [paypal/paypal-checkout#333]
What would cause the old UI to load into the new popup window generated by this script? I just had this happen. It is pretty random, but wondered if there was something I could do to make this not happen .... ever.

I did notice that it took a long time to load, then it's like it gave up and showed the old crap standard UI.

**Comment by bluepnume** [comment]
Is it happening on sandbox or production env?

**Comment by yabdab** [comment]
Production

**Comment by bluepnume** [comment]
Do you happen to see any errors in the browser console?

This experience is shown when we encounter a fatal error with the checkout app, and have to go into recovery mode. It's due to be phased out in the coming months -- it should be pretty rare, but if we can narrow down the specific error that should give us some more info.

**Comment by yabdab** [comment]
No, but I will try and reproduce to see if I can reproduce.

But, if this is a non-issue in a few months, then it may not be worth your time to fix anyway.

I will post anything I find here if it happens to me again.

Thanks.
