### ISSUE TITLE
iOS SFSafariViewController not working with Paypal

### ISSUE THREAD

**Issue by dansl** [paypal/paypal-checkout#347]
We are trying to get our sites working in SFSafariViewController, but it's breaking PayPal and only showing a blank page. Google Maps recently switched to using SFSafariViewController in their iOS app, and our sites get heavy traffic from the Google Maps iOS app, which is causing issues with Paypal checkout... Any help would be appreciated!

**Comment by bluepnume** [comment]
Hi @dansl -- yeah, this is a known issue, which is exacerbated by the fact that (to the best of my knowledge) it's virtually impossible to programatically differentiate between Safari and an SFVC. 

Let me check and see if there's anything new that'll help us get this to work.

**Comment by eni9889** [comment]
@bluepnume have there been any new findings on this? With iOS 11 right around the corner it will be necessary to support SFSafariViewController

**Comment by bluepnume** [comment]
@eni9889 we raised http://www.openradar.me/31117000 but have yet to hear anything back from Apple. In the mean time, if you come up with any way to determine that it's an SFVC, I'll happily add support here.

**Comment by andreabondi** [comment]
Update on this: since iOS 11, SFSafariViewController supports window.open (see https://developer.apple.com/videos/play/wwdc2017-225/?time=979 minute 16:20).

This means that checkout.js will work correctly on SFSafariViewController on devices with iOS 11. I tested and behaviour is as expected, for both Payment Authorised and Cancelled.

As measured on the 18th January 2018 iOS 11 is used by 65% of devices (see https://developer.apple.com/support/app-store/ ).

**Comment by bluepnume** [comment]
That is **fantastic** news, thanks so much @andreabondi!

**Comment by kraisorns** [comment]
@benmurden I got a blank screen when running on iOS Simulator 10.3.1 but iOS 11.4.xx work fine.
