### ISSUE TITLE
Button displayed incorrectly when using  browser zoom

### ISSUE THREAD

**Issue by Klavius** [paypal/paypal-checkout#355]
For chrome when  zooming to 110%  on a 'small' button, it is displayed like this

![image](https://cloud.githubusercontent.com/assets/11545536/26361412/8540a7ba-3fa0-11e7-9744-c894c1a837b2.png)

**Comment by ryandemmer** [comment]
Not sure if it is related to this commit - https://github.com/paypal/paypal-checkout/commit/7646eee62b6e0f2e52fe2e0b17ac9e6314367a62 - but now the buttons disappear when the browser is zoomed.

On this page - https://developer.paypal.com/demo/checkout/#/pattern/styles - in Chrome go to View -> Zoom In and the checkout button disappears. The same happens when using View -> Zoom -> Zoom In in Firefox.

This appears to trigger media query rules in the inline styles, hiding the button.

**Comment by bluepnume** [comment]
This is now fixed and pushed.
