### ISSUE TITLE
Server Side Rendering compatibility (check if window exists)

### ISSUE THREAD

**Issue by f2net** [paypal/paypal-checkout#362]
I appreciate that the latest releases are more webpack/React friendly.

Unfortunately, paypal-checkout uses "window" in many points without checking if window is available, so it breaks on the first server side rendering.
Of course the Paypal button is shown only client-side, but the library cannot be used because "window is undefined".

Now I load the CDN checkout.js script asyncronously using react-async-script-loader and set a showButton flag on the local state only if the script is correctly loaded (check in componentDidMount and willReceiveProps) and also set React/ReactDOM on the window global. Unfortunately this solution isn't stable enough (our customers say that many clients call because the button isn't showing, it throws errors etc).

I'd like to use the new 4.0.78 library with WebPack instead, but it is impossibile for a server-side rendering project (and I think any e-commerce based on React should be SSR to be SEO-friendly).

I think it is enough to check if window exists before calling any method on window. Do you think it is feasible?

Thank you,
Matteo Frana

**Comment by bluepnume** [comment]
Hmm, good question.

It might be possible but would require some pretty extensive changes through all of the dependencies for paypal-checkout.

For now can you do a conditional require?

```javascript
if (typeof window !== 'undefined') {
    let paypal = require('paypal-checkout');
}
```

**Comment by f2net** [comment]
Thank you Daniel,
I'm using the conditional require now and everything seems ok in dev/sandbox.
Tomorrow I'll test it in a production environment.

Anyway, I'd leave the issue open as a Feature request, because I think that having the component working in a React SSR environment would be an shared need.

Thank you for your work,
Matteo

**Comment by bluepnume** [comment]
Glad it works! So, in terms of officially supporting SSR, I'm not totally convinced, since this intended to be a 100% client-based library. So, if it's required on the server-side, it's going to fail at some point, whether it's on `require()` or on calling `paypal.Button.render()`. I could check for `window` everywhere and export no-ops, but that would just move the failure point to later.

Seems to me like it's cleaner if it's just up to clients to do a `typeof window` check. Otherwise I'm not sure what the cleanest behavior for this lib would be.

**Comment by nwallis** [comment]
Original poster no longer exists - but I am curious how important SSR is for SEO in 2019.
