### ISSUE TITLE
angular 4 and paypal express checkout

### ISSUE THREAD

**Issue by kodermax** [paypal/paypal-checkout#368]
How Can I integrate angular4 and paypal?

**Comment by bluepnume** [comment]
Hi @kodermax -- don't currently have support for angular 4, but you can check here for progress:

https://github.com/krakenjs/xcomponent/issues/23

In the mean time, you should be able to use the button with just a regular `paypal.Button.render()` somewhere in your angular controller, I'm sure.

**Comment by kodermax** [comment]
What method should I use on Angular4?

**Comment by alaaeddinezammel** [comment]
any news ?

**Comment by bluepnume** [comment]
Hi -- I don't have any official docs for this yet, but angular2+ support was just added to xcomponent, which powers paypal-checkout: https://medium.com/@harouny/introducing-xcomponent-support-for-angular-2-cb31a89f01 (thanks @harouny)

So you should be able to do something like:

```javascript
import * as ngCore from '@angular/core';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from './app-component';

let PayPalButtonModule = paypal.Button.driver('angular2', ngCore);

@NgModule({
    imports: [ BrowserModule, PayPalButtonModule ],
    declarations: [ AppComponent ],
    bootstrap: [ AppComponent ]
})
export class AppModule {
    constructor () {
    }
}
```

Then in your template:

```javascript
<paypal-button [props]="{ payment: payment, onAuthorize: onAuthorize }"></paypal-button>
```

I haven't personally tested the paypal button component with angular 2 yet, so please let me know if you see any issues.

**Comment by carlosost** [comment]
Hello @bluepnume,

Any news about an specific documentation on how to use paypal-button on Angular2+? 

Would be awesome to have something explaining the process since the "npm install paypal-checkout" to the use of the ta <paypal-button>.

I've tried the suggestion above, but I am getting an "Uncaught ReferenceError: paypal is not defined" on paypal.Button.driver....

Regards.

**Comment by bluepnume** [comment]
I'll try to get to this soon. In the mean time did you add the checkout.js script somewhere on your page?

```html
<script src="https://www.paypalobjects.com/api/checkout.js"></script>
```

**Comment by carlosost** [comment]
I've just added the checkout.js script to index.html and `<paypal-button [props]="{ payment: payment, onAuthorize: onAuthorize }"></paypal-button>` to the page I need the button to be rendered, but now I am getting a new error -> ERROR Error: Prop is required: payment

It is not your fault of course, but that is what I am talking about. As I am new with all this stuff of xcomponent, Angular, etc and still need more complete instructions :-(.

Well.. I think I need to read once more all the documentation available.

Regards.

**Comment by bluepnume** [comment]
> How to, at MyPayPalComponent.ts, "overload" the functions payment, onAuthorize and on Cancel, to make everything work?

You should be able to implement these functions in the exact same way as in the examples at https://developer.paypal.com/demo/checkout/#/pattern/client -- there's nothing specific to Angular here.

But yep, will try to get a demo up for angular4 as soon as possible -- I'll reopen this issue in the mean time.

**Comment by alaaeddinezammel** [comment]
@bluepnume  i wish u put a demo with angular 4 those days

**Comment by srinivastamada** [comment]
@carlosost You got any solution for PayPal

**Comment by bluepnume** [comment]
Demo is now up here: https://github.com/paypal/paypal-checkout/blob/master/demo/angular2.htm

**Comment by mjstecson** [comment]
@bluepnume How do you change the value of the amount total in payment based on a variable from the component? Changing `total: '1.00'` to `total: this.someVar` is returning a VAILDATION_ERROR.

**Comment by alaaeddinezammel** [comment]
im using angular 4 

im getting an error in app.module when i put 
 paypal.Button.driver('angular2', ng.core) in ngModule import

**Comment by mjstecson** [comment]
@carlosost I followed your steps and did my own config for the paypal-button props. 
in component.html:
`<paypal-button [props]="paypalConfig"></paypal-button>`

in component.ts:
`paypalConfig = { 
    env: 'sandbox',
    client: {
      sandbox:    'xxxxxxxxxx',
      production: 'xxxxxxxxxx'
    },
    commit: true,
    payment: (data, actions) => {
      return actions.payment.create({
        payment: {transactions: [{amount: {total: this.amount, currency: 'USD'}}]}
      });
    },
    onAuthorize: (data, actions) => {
      return actions.payment.execute().then(() => {
        /*show success*/
      });
    }
  };`

If working perfectly now but when I tried to do `ng build --prod` it returned an error:
`ERROR in Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'paypal'. Consider exporting the symbol (position 14:15 in the original .ts file), resolving symbol PayPalButtonModule in /../../../../src/app/app.module.ts, resolving symbol AppModule in /../../../../src/app/app.module.ts, resolving symbol AppModule in /../../../../src/app/app.module.ts`

Does this also happen to you? If so, do you have a solution/workaround on this?

Regards.

**Comment by bluepnume** [comment]
Could you do something like `declare var paypal: any;` ?

**Comment by mjstecson** [comment]
@bluepnume I believe your reply was for @alaaeddinezammel 

On my case, I have 

> `declare const paypal: any;` 

in my app.module.ts followed by 

> `export const PayPalButtonModule = paypal.Button.driver('angular2', { Component, NgModule, ElementRef, NgZone });`

Then imported PayPalButtonModule
>`@NgModule({`
`  ...`
`  imports: [..., PayPalButtonModule],`
`  ...`
`})`

**Comment by alaaeddinezammel** [comment]
![image](https://user-images.githubusercontent.com/21026490/29924643-def92082-8e5d-11e7-82e4-f1007b5899e6.png)


![image](https://user-images.githubusercontent.com/21026490/29924752-483f3a2c-8e5e-11e7-9bcd-6ea19f3fa8a6.png)

that's awkward  still not working guys  @bluepnume  @mjstecson

**Comment by mjstecson** [comment]
@alaaeddinezammel import Component, ElementRef and NgZone from @angular/core.

Just put them beside where you imported NgModule.

After that, it should fail to compile on the first ng serve, having the reference to a local non-exported symbol error, but will successfully compile when you save other changes.

It works perfectly in dev but when I try to build it for prod, it always fail on the non-exported error. Adding export in the `declare const paypal: any` line produces another error. Not sure on how to go about it. @bluepnume

**Comment by keeperofchem** [comment]
@mjstecson After tinkering with this all day, I believe I have found a temporary solution.

Instead of exporting a PaypalButtonModule in the app.module and dealing with the failed AOT compilation, I had the following setup in the component wherein I used the paypal button.

Outside the component, in the same scope as the import statements:

`declare let paypal: any;`

Next, declare a class boolean to keep track of whether or not the button rendered:
`private didRenderPaypal: boolean = false`

Then, make a class method to manually load the paypal script and insert it into the DOM:
`private loadPaypalScript(): Promise<any> {
    this.didRenderPaypal = true;
    return new Promise((resolve, reject) => {
      const scriptElement = document.createElement('script');
      scriptElement.src = 'https://www.paypalobjects.com/api/checkout.js';
      scriptElement.onload = resolve;
      document.body.appendChild(scriptElement);
    });
  }`

In your component template, insert `<div id="paypal-btn"></div>` wherever you want the button.

Finally, in ngAfterViewChecked (remember to import AfterViewChecked and implement it):

`ngAfterViewChecked() {
    if(!this.didRenderPaypal) {
      this.loadPaypalScript('assets/scripts/paypal-checkout.js').then(() => {
        paypal.Button.render(this.paypalConfig, '#paypal-btn');
      });
    }
 }`

Let me know if this works for you.
P.S. Sorry for bad formatting, first time commenting

**Comment by harouny** [comment]
I haven't had time to try this but I have seen this AOT issue before. Could you guys try something like this in app.module.ts:

declare let paypal: any;

then:

export paypal;

or 

export paypal.Button;

and see if that fix the issue.

**Comment by mjstecson** [comment]
@harouny `export paypal;` and `export paypalButton` returns a 'Declaration or statement expected' errror.

@keeperofchem Your workaround works! 😄  Thanks for looking into this! 😄

**Comment by harouny** [comment]
@mjstecson 
Sorry may bad, I meant:
```
export { paypal };
```

**Comment by harouny** [comment]
@mjstecson 
I have updated my comment, and will try it myself now

**Comment by harouny** [comment]
@mjstecson Sorry my proposal doesn't work. Paypal.Button angular2 component currently doesn't work when AOT is enabled.

**Comment by harouny** [comment]
@mjstecson @keeperofchem @bluepnume 

The following is an example of an angular cli project using ```paypal-button``` angular component:
https://github.com/harouny/paypal-button-ng2

Notice that I pass ```-aot false``` to ```ng -build``` to avoid ahead of time compilation.

**Comment by bluepnume** [comment]
Thanks @harouny! Feel free to PR in a link to this to https://github.com/paypal/paypal-checkout/blob/master/docs/frameworks.md and I'll gladly merge.

I haven't had a lot of time to follow the discussion -- but do we know why AOT causes this to fail? Is it something we can fix in xcomponent or this repo?

**Comment by keeperofchem** [comment]
@harouny Unfortunately, I think AOT is a bit too important towards production, since the speed difference is fairly noticeable. For now I'll be using my work around, until a better solution is presented (my solution takes quite a long time to load, since it is loading a script into the DOM). Not really worth it to slow down the whole project for a paypal button though. 

@bluepnume From what I understand, because typescript is almost a typed language, the AOT does a static scan of your code to ensure that it will compile. Using a statement such as `declare let paypal: any;` will confuse the AOT since it is not exported yet imported into NgModule, whereas exporting the paypal variable makes the AOT uncomfortable since it is not clearly defined. This problem seems fairly common with including other (weakly typed) javascript libraries in typescript, so I am not sure it will be easy to fix in this repo.

**Comment by harouny** [comment]
@keeperofchem Yes, you are right. The JIT way is not for every project. That's why AOT is default now.

@keeperofchem @bluepnume 

The problem is more than fixing ```declare let paypal: any;``` issue.
As @keeperofchem said,  AOT pre compiles components before they can be used at runtime. In AOT mode, angular compiler is not even available at runtime.  That's why AOT requires imported modules/components to be statically available at compile time.
In our case we load the module via script tag at runtime. Which means neither the module nor the component referenced [here](https://github.com/harouny/paypal-button-ng2/blob/master/src/app/app.component.html#L2) is available at compile time.

I'm still investigating if there is a way to dynamically load the component at runtime and let the rest of the app use AOT, I will keep you posted if I found a solution.

**Comment by keeperofchem** [comment]
@harouny @bluepnume 

https://github.com/keeperofchem/ng4-paypal-button 
Repo containing an example of AOT passing paypal button integration. The paypal script is dynamically injected into the DOM at runtime to bypass AOT; note the slight delay on the rendering of the button.

**Comment by harouny** [comment]
Thanks @keeperofchem 

Just to be clear, we have two ways of integration:
- [Basic Integration](https://github.com/paypal/paypal-checkout/blob/master/docs/button.md#basic-integration)
- [Native framework bindings](https://github.com/paypal/paypal-checkout/blob/master/docs/button.md#native-framework-bindings) 

This issue here is related to native framework bindings (using a native angular component), your code sample (and your workaround) belongs to basic integration (directly render component to DOM using the ```render``` function).

**Comment by kandyjam** [comment]
@keeperofchem can you tell me any idea for ng4 implements this way?
https://developer.paypal.com/demo/checkout/#/pattern/server

**Comment by usamamalik75** [comment]
@carlosost 
Thanks i follow you steps and now paypal checkout working
but one problem after payment successful Router object undefined
some sample code

>  onAuthorize(data: any, actions: any) {
>         debugger
>         return actions.payment.execute().then(function () {
>             // Show a success page to the buyer
>             console.log("onAuthorize");
//// after successful payment "router" object show undefined
>             this.router.navigate(['abc',id]);
>         });
>         
>     }

**Comment by gate3** [comment]
Hi guys, thanks for the tip. I implemented it and it works. But my question is how does one go about recurring payments?

**Comment by subramaniashiva** [comment]
Waiting for paypal + Angular4 integration library. Meanwhile I implemented it by calling paypal.Button.render function in the component where I needed paypal integration

**Comment by alexthelion** [comment]
Hi guys! Is there any way to catch and display error messages with onError method.
I want to display an error message to the user with the wrong field. With the current error message structure i can't extract the problematic fields.
I'm getting an error like this:

Error: Error: Request to post https://www.sandbox.paypal.com/v1/payments/payment failed with 400 error. Correlation id: 588c6ae350e0, 588c6ae350e0

{
    "name": "VALIDATION_ERROR",
    "details": [
        {
            "field": "zip",
            "issue": "Value is invalid"
        }
    ],
    "message": "Invalid request - see details",
    "information_link": "https://developer.paypal.com/docs/api/payments/#errors",
    "debug_id": "588c6ae350e0"
}

    at XMLHttpRequest.<anonymous> (https://www.paypalobjects.com/api/checkout.js:15187:39)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:3160:122)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:3059:77)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:3080:13)
    at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:425:31)
    at Zone.runTask (webpack-internal:///../../../../zone.js/dist/zone.js:192:47)
    at ZoneTask.invokeTask [as invoke] (webpack-internal:///../../../../zone.js/dist/zone.js:499:34)
    at invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:1540:14)
    at globalZoneAwareCallback (webpack-internal:///../../../../zone.js/dist/zone.js:1577:21)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:3160:122)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:3059:77)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:3080:13)

    at XMLHttpRequest.<anonymous> (https://www.paypalobjects.com/api/checkout.js:15187:39)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:3160:122)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:3059:77)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:3080:13)
    at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:425:31)
    at Zone.runTask (webpack-internal:///../../../../zone.js/dist/zone.js:192:47)
    at ZoneTask.invokeTask [as invoke] (webpack-internal:///../../../../zone.js/dist/zone.js:499:34)
    at invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:1540:14)
    at globalZoneAwareCallback (webpack-internal:///../../../../zone.js/dist/zone.js:1577:21)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:3160:122)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:3059:77)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:3080:13)
    at deserializeError (https://www.paypalobjects.com/api/checkout.js:3668:20)
    at https://www.paypalobjects.com/api/checkout.js:3687:322
    at https://www.paypalobjects.com/api/checkout.js:3779:30
    at eachArray (https://www.paypalobjects.com/api/checkout.js:3762:51)
    at each (https://www.paypalobjects.com/api/checkout.js:3768:35)
    at replaceObject (https://www.paypalobjects.com/api/checkout.js:3778:13)
    at https://www.paypalobjects.com/api/checkout.js:3780:169
    at eachObject (https://www.paypalobjects.com/api/checkout.js:3765:65)
    at each (https://www.paypalobjects.com/api/checkout.js:3768:144)
    at replaceObject (https://www.paypalobjects.com/api/checkout.js:3778:13)

**Comment by jhourlad** [comment]
After a year: 2018. Angular 5 out. Still no Angular 4 support :D :D :D

**Comment by carlfm01** [comment]
@KevinShiCA Thanks, working with Angular 5, @jhourlad take a look https://github.com/KevinShiCA/ng4-paypal-button

**Comment by svenkat18** [comment]
How to implement confirm payment button in Angular 4 ?
https://developer.paypal.com/demo/checkout/#/pattern/confirm

When user clicks on "Payment Checkout" call return actions.payment.get().then(function(data) ..
and then user clicks on "complete payment" ....then call actual execute method 
 return actions.payment.execute().then(function()
