### ISSUE TITLE
Allow pulling in this package via NPM. Don't push breaking backend changes

### ISSUE THREAD

**Issue by feeekkk** [paypal/paypal-checkout#380]
In the [ documentation ](https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/add-paypal-button/) it is strictly mentioned to only reference this library via `https://www.paypalobjects.com/api/checkout.js`. 

Doing so does not protect our application against breaking javascript changes between versions of this library.

However, pulling in our own version via npm resulted in another application of ours breaking on Friday morning. Upgrading it from 4.0.36 to 4.0.82 resolved the issue. I'm speculating, but I'm assuming our application eventually broke Friday morning due to backend Paypal API changes.

**The current system of including this library is a catch 22:**
1) Pull in this library from PayPal's CDN and be victim to this client pushing breaking front-end changes. OR
2) Pull in this library via NPM and risk (unknowingly) being on an unsupported version that breaks when PayPal updates its backend API without support for older versions.

I believe the most standard solution is to have this library follow [semantic versioning](http://semver.org/), and provide backend API support for previous versions (while providing notice of version deprecation so devs have time to upgrade their apps). It would also be nice to have release notes / upgrade guide for each release. As we upgraded our app from 4.0.36 to 4.0.82 we ran into breaking changes that do not belong in patch releases and had to track down what changes were made in code.

If this is not an option, what do you recommend? 

Thanks.

**Comment by bluepnume** [comment]
Hi @feeekkk 

Our goal is to be 100% backwards compatible, given that so many merchants are already integrated with our CDN. That should include any server-side changes.

Can you elaborate on the issue you saw with `4.0.36`? I'd like to track that down as there may be others using that version.

I would still recommend using the CDN url rather than npm, given:

1. There should be absolutely no breaking changes in the public api provided by checkout.js

2. This also gives you a site-speed increase -- checkout.js is also loaded inside the checkout and button iframes / popups, so using the CDN version means your customers get a cached version when they hit the paypal app

**Comment by feeekkk** [comment]
RE point 1:

There unfortunately was a breaking change that we came across while upgrading patch versions. I think it was from the resolution of this issue https://github.com/paypal/paypal-checkout/issues/136 (which would have been a `major` bump in semver)

IE we had to change our implementation from `paypal.ppxo.checkout.setup` to `paypal.checkout.setup`. Some release notes or upgrade guide for this would have been nice!

---

The issue that we saw with `4.0.36` that we discovered on Friday:

```
Refused to display 'https://www.paypal.com/webapps/hermes/fallback?product=ec&fallback=1&reason=ui_unhandled_typeerror&token={redacted}' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```

This was resolved when upgrading to the latest version.

**Comment by bluepnume** [comment]
`token={redacted}` -- can you share the token? Then I can find the error. It's totally harmless to share.

I'm sorry about the `paypal.ppxo` change -- you're right, that should have been a major bump. I'm really sorry about the inconvenience there.

**Comment by feeekkk** [comment]
Sorry, wanted to err on the safe side.

https://www.paypal.com/webapps/hermes/fallback?product=ec&fallback=1&reason=ui_unhandled_typeerror&token=EC-3HT5503439288842X

Thanks for looking into it!

**Comment by bluepnume** [comment]
Aha yep. I see the error -- it's one that we identified already, and the fix is going out with the next release of the checkout web-app. 

This kind of issue is tricky to solve with versioning alone, since it relies on something like:

- New version of checkout.js adds a new prop which can be passed down in `paypal.Button.render()`, like `someCallback`
- Child window consumes `window.xprops.someCallback()`
- Works great for new versions of checkout.js where `someCallback` has some default set, but gives a null-pointer for old versions

Since the checkout webapp itself can't be easily versioned, the best thing we can do about issues like that is:

- Null checks for anything consumed in the webapp from checkout.js
- Better testing

Normally we've been pretty good about the null checks and testing, but this one slipped through the cracks. Again, apologies about that.

**Comment by feeekkk** [comment]
So I guess this core issue is the "webapp itself can't be easily versioned" 😛 

For now I see the safest thing for us to do is pull in directly from the CDN, however I am not a fan of this approach as it doesn't protect our application from any breaking public API changes in the CDN version that could potentially occur in the future.

Thanks for looking into the issue with `4.0.36` so quickly, however this was a critical issue for us so we updated ASAP.

**Comment by bluepnume** [comment]
Sounds good for the time being. For what it's worth, any breaking changes in the public api would definitely be considered a bug, and we have 600+ tests for all of the public apis we expose through checkout.js, so I'm hoping this should be a pretty safe option for you.
