### ISSUE TITLE
onAuthorize never gets called, but order goes through?

### ISSUE THREAD

**Issue by yabdab** [paypal/paypal-checkout#381]
I have had this happen a few times. I am not sure if the buyer is using an old browser like IE 7 - 9  or what? So if, the onAuthorize experiences an error and cannot fire, is there another way to query the order details?

Is there a silent POST style callback we can use to avoid any browser errors breaking the final checkout action?

Thanks.

**Comment by trainerbill** [comment]
Here is the browser support for the library.  https://github.com/paypal/paypal-checkout/blob/master/src/config/config.js#L42  If the browser is unsupported you shouldn't get a paypal button to render so I don't think that is the issue.

I don't think it is possible to get a payment without calling payment.execute which is called in the onAuthorize callback.  You should wrap whatever you are doing before payment.execute ina try/catch statement so that it continues on error and then call the payment.execute.  If you need help with your integration you can go to our gitter room.

https://gitter.im/paypal/paypal-checkout
