### ISSUE TITLE
PayPal login redirecting to PayPal account page and not PP checkout review page

### ISSUE THREAD

**Issue by murugesans** [paypal/paypal-checkout#423]
### Description
Using Live environment having issue with PayPal checkout and working fine in sandbox. 
We are using ECJSv4 client side code.

Please provide each individual step required to reproduce the issue
1. Click PayPal checkout button
2. PayPal In context came
3. Login with PayPal credentials
4. Observation - Redirected to PayPal account setup 
   Expectation - PayPal checkout review page
### Affected browsers

- Tried with Chrome

![image](https://user-images.githubusercontent.com/30517176/28702648-fdb9de50-737b-11e7-89bb-3aa8ff26a86f.png)

![image](https://user-images.githubusercontent.com/30517176/28702665-1cf95c96-737c-11e7-8103-02c7832bc678.png)

![image](https://user-images.githubusercontent.com/30517176/28702671-27d26cac-737c-11e7-8df5-94b3b6229850.png)

Thanks,
Murugesan
musekar@paypal.com

**Comment by murugesans** [comment]
Tried the test website url on my end and it is working with Chrome, FireFox & IE11 browser. Issue with the Buyer PayPal account. Tried with different PayPal account and it seems working.

**Comment by carloxavier** [comment]
Hi! we are looking into a similar issue, is there a way to prevent this?

**Comment by MarcoBlulab** [comment]
Since I activated two-factor authentication, I systematically have this same problem throughout all e-commerce I buy that use a popup for paypal payments. I am redirected to the paypal account page instead of the checkout review page.
It is a general problem of Paypal, which loses the redirect URL when more than one page of Paypal is shown to the user (e.g. login + auth code in another step), therefore this error persists despite being reported since 2017: it's difficult to replicate beacause depends a lot on the status of the account you are using and how you are logged in.
