### ISSUE TITLE
PayPal button wrapper clears when loading in a modal

### ISSUE THREAD

**Issue by quinnjn** [paypal/paypal-checkout#425]
### Description

I've tried using a jquery modal library called [bPopup](https://github.com/dinbror/bpopup) to display the button in a modal. The button generates in the button wrapper hidden OK. When asking the modal to open the button wrapper div clears out and the PayPal button is removed.

I've also reproduced this with another modal library called [jquery-modal](https://github.com/kylefox/jquery-modal).

Versions:
- checkout.js 4.0.96
- braintree.client 3.20.1
- braintree.paypalCheckout 3.20.1

### Steps to reproduce

I've created a [codepen](https://codepen.io/quinnjn/pen/prjNJZ) using bPopup that demonstrates the problem.

### Affected browsers

The button doesn't load on Chrome, Safari, Firefox. The button does load on IE.

- [X] Chrome
- [X] Safari
- [X] Firefox
- [ ] IE

**Comment by bluepnume** [comment]
Think I see what's happening here. The button iframe is being removed from the dom and then being re-added. This causes the inner window to close and then re-open. That's problematic because the parent window is listening for messages from the original window, and assumes that the window has been destroyed -- hence it cleans up the iframe and any other state on the page.

There may be a hacky fix for this, but I guess my advice for now would be to render the button after the modal has been opened.
