### ISSUE TITLE
PayPal button size responsive isn't 100%

### ISSUE THREAD

**Issue by PWaddict** [paypal/paypal-checkout#446]
I'm using the responsive size on PayPal button and it doesn't have 100% width. The highest I get is 500px and I need a real 100% width. Is there a way to achieve it???

![paypal-button](https://user-images.githubusercontent.com/23142666/29462414-f2adb3b6-8437-11e7-9a52-e5c15a4ac462.jpg)

**Comment by PWaddict** [comment]
@bluepnume please increase the max-width of the button. I need it at least 660px. Thanks.

**Comment by bluepnume** [comment]
We're mooting whether we want to increase the max size.

Bear in mind, this is designed to be a button element with a fixed aspect-ratio, and the higher we go in terms of width, the more specific rules need to be added to keep the button aligned with our UX guidelines.

Does a centered button not fit in ok with your design here?

**Comment by PWaddict** [comment]
I'm only asking to have 100% width on the responsive size. Above 500px don't adjust anything else like button's text, logo etc, only the width of the button so it can fit nicely on layouts like my own cause currently it looks amateur/unprofessional with the empty space on left/right since all my elements are using 100% width.

If anyone wants fixed size button should use small, medium or large but responsive should definitely have 100% width.

**Comment by bluepnume** [comment]
We've expanded the max width of the button to 750px. Please let me know if you see any issues. Thanks!

**Comment by PWaddict** [comment]
It works perfect! Thank you very much :)

**Comment by rdunk** [comment]
Would like to request that this issue is reopened as the responsive label is somewhat confusing for a button that is not fully responsive. For example we have a situation where buttons occupy 50% of the width of the viewport. On larger screens the PayPal button looks out of place because of the enforced maximum width.

I understand the need to conform to PayPal's UX guidelines, but as the button is actually _intended_ for use outside of the context of PayPal's UI it seems kind of strange to restrict flexibility by enforcing a specific pixel width—especially as this is the only way to initialise the express checkout flow (as far as I'm aware, would be great to hear if I'm wrong about that).
