### ISSUE TITLE
merchant redirected to their website inside iframe/popup after pay btn

### ISSUE THREAD

**Issue by vishakha94** [paypal/paypal-checkout#450]
Merchant says his Shopify using the checkout.js, sometimes redirects to the
payment page as it should, and sometimes redirects to their main website.
I could verify this myself, by testing their website, and try to pay using PayPal.
https://shop.palaceskateboards.com
If you can verify this, since I'm not finding any javascript errors, nor network issues nor
posts in the github repo.
Thanks
Steps to reproduce issue:
1- Pretend to buy using PayPal at https://shop.palaceskateboards.com
2- See the popup sometimes redirects to PayPal and sometimes does not.
Additional Inputs:
Merchant Inputs:
Account Number: 2049865619267244317
Recent Examples:
![capture1](https://user-images.githubusercontent.com/12112794/29797130-559eb3ba-8c0a-11e7-860a-b2b84d6d29a3.PNG)
![capture2](https://user-images.githubusercontent.com/12112794/29797131-55a02d3a-8c0a-11e7-89c6-233a686902b2.PNG)
![capture3](https://user-images.githubusercontent.com/12112794/29797132-55a68482-8c0a-11e7-8dc5-ed5a78b8e934.PNG)

**Comment by bluepnume** [comment]
This is a bug on the merchant side. The integration is a v3 style integration

- Merchant passes checkout.js a url
- checkout.js redirects to that url in the popup window
- That url needs to do a 302 to paypal.com/checkoutnow

In this case the merchant is not doing this redirect correctly, and is returning a 200 response rather than a 302:

<img width="1442" alt="screen shot 2017-08-29 at 4 35 49 pm" src="https://user-images.githubusercontent.com/1219075/29849161-de97a774-8cd9-11e7-9a6e-0581e9873c36.png">
<img width="1414" alt="screen shot 2017-08-29 at 4 37 13 pm" src="https://user-images.githubusercontent.com/1219075/29849160-de96748a-8cd9-11e7-9d83-8663fd94c54d.png">

In the successful case I do see a 302 to paypal.com, as expected:

<img width="1257" alt="screen shot 2017-08-29 at 4 41 37 pm" src="https://user-images.githubusercontent.com/1219075/29849174-ebcfd506-8cd9-11e7-947d-6b5f34b0f73a.png">

The merchant needs to ensure they consistently redirect to paypal.com, otherwise the url which loads in the minibrowser will not be the checkout experience.

**Comment by ryanmof** [comment]
I have reached out to the Shopify PM to look into this bug.
