### ISSUE TITLE
Invalid prop: style ?

### ISSUE THREAD

**Issue by yabdab** [paypal/paypal-checkout#492]
Starting to get this error a few minutes ago?

_Uncaught Error: [paypal-checkout] Invalid prop: style ..._

Can we please stop dropping props with no notice?

**Comment by bluepnume** [comment]
@yabdab -- can you please do a cache clean and make sure you have the latest `checkout.js`?

This isn't a dropped prop. It's because `style` was added as a new internal prop for the `Checkout` component, but it's not being recognized for older versions of `checkout.js`. For now this problem should be limited to sandbox, and should be fixable with a cache clean.

Thanks!

**Comment by melwas** [comment]
I also noticed the same error minutes ago. [Demo](https://developer.paypal.com/demo/checkout/#/pattern/checkout) page does not work either.

**Comment by bluepnume** [comment]
@melwas -- I know it's not ideal, but does clearing your cache solve the problem for you?

**Comment by melwas** [comment]
@bluepnume I deleted the previous comment because I thought the cache should fix the issue, but it seems that it does not. After clearing the cache the demo page still does not work for me. Checked it on Chrome, Firefox and Safari...

**Comment by bluepnume** [comment]
OK, thanks for the heads up. For now I'm rolling back the sandbox changes while I investigate this.

**Comment by yabdab** [comment]
Doing a hard reset and cache clear in Chrome worked for me. Will keep an eye on it.

**Comment by yabdab** [comment]
I assume this has to do with new funding icons art?

**Comment by bluepnume** [comment]
That's part of the next release, yes. But not directly the cause of this issue.

**Comment by bluepnume** [comment]
OK, rollback is complete.
