### ISSUE TITLE
Paypal button does not display on MS Edge

### ISSUE THREAD

**Issue by giuliamatozza** [paypal/paypal-checkout#557]
### Description

Observe missing label on the Paypal button
![image](https://user-images.githubusercontent.com/19781141/33937743-885cd5fc-dffc-11e7-9fed-a55fd22de2db.png)

### Steps to reproduce

Go to https://staging.rnib.panlogic.co.uk/donations-and-fundraising
Check the donate promo and look at the button next to Donate with card
The Paypal label is missing

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X ] Edge
Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299 Microsoft 2017
Windows 10
HP Pavilion
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
This was resolved by email -- looks like the site's CSP policy is blocking the logo. Need to allow `data:` in the `img-src` CSP directive.

**Comment by flrent** [comment]
We had the same issue and spent quite some time debugging, having fairly strict CSP policies. 

Turns out the PayPal icon is an external SVG rendered as a base64 image in a iframe. Until *today*, there was a bug when using `frame-src self` in Edge <= 41. They patched it in 42 and released it on April 30. https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8690562/

Hope that helps!
