### ISSUE TITLE
Jquery usage in examples:

### ISSUE THREAD

**Issue by gety9** [paypal/paypal-checkout#588]
In advanced integration example jquery is used:

        payment: function() {
            return new paypal.Promise(function(resolve, reject) {
                jQuery.post('/my-api/create-payment')
                    .done(function(data) { resolve(data.paymentID); })
                    .fail(function(err)  { reject(err); });
            });
        },

Is there a reason for this? On the paypal demo page they have:

            payment: function() {
                var CREATE_URL = '/demo/checkout/api/paypal/payment/create/';
                return paypal.request.post(CREATE_URL)
                    .then(function(res) {
                        return res.paymentID;
                    });
            },

**Comment by bluepnume** [comment]
You're free to do either -- `paypal.request.post()` is just a helper function to make an ajax call. All the `payment()` function cares about, is that you return some kind of promise which resolves to a paymentID. But I'll leave this open as a reminder to update those docs, since `paypal.request.post()` does make this easier.

**Comment by artofspeed** [comment]
@gety9 Well it's just that with jQuery you'll have more flexibility and ability to customize according to your needs, ex: change dataTypes, add timeout, use FormData, etc. Whereas `paypal.request.post()` is a shortcut offered to get things done quickly. But you can use any HTTP libraries of your choice, Axios, Fetch API, jQuery.ajax(), etc.
