### ISSUE TITLE
Script Incompatibility with checkout.js 

### ISSUE THREAD

**Issue by ballawzi-pp** [paypal/paypal-checkout#624]
### Description
An e-commerce platform has received complaints from their merchants that the checkout.js button is opening then closing immediately. They have provided the following sites to mock up the cases in which the behaviour is occurring:

http://lamp.ecwid.com/~borman/paypal_1.html 
http://lamp.ecwid.com/~borman/paypal_2.html 

It seems to be related the scripts in the header blocking some of the checkout js functionality (as when removed it works).
Although, the errors of the different examples result in different errors:
ppxo_unhandled_error ; Uncaught Error: TypeError: Cannot read property 'result' of undefined
ppxo_unhandled_error ; Uncaught Error: Expected payment id or token to be passed, got undefined

### Affected browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge
- [x] IE
- [x] Chrome Mobile/Tablet
- [x] Safari Mobile/Tablet
- [x] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Found the issue.

In http://www.spargophoto.com.au/universal/scripts/global.js?CE=75

```
Function.prototype.bind = function(I, N, M, L, J, H, G, F, C, B, A) {
    var K = this;
    return function() {
        K.apply(I, [N, M, L, J, H, G, F, C, B, A]);
    }
    ;
}
```

This `Function.prototype.bind` polyfill is totally broken. It's not returning anything. It should be:

```
Function.prototype.bind = function(I, N, M, L, J, H, G, F, C, B, A) {
    var K = this;
    return function() {
        return K.apply(I, [N, M, L, J, H, G, F, C, B, A]);
    }
    ;
}
```

Or better yet, don't polyfill this, it's available in every browser that's supported by checkout.js.

**Comment by qetzal** [comment]
Hi @bluepnume,
Unfortunately it doesn't solve the issue. Please let me explain why (we found the problem initially)

1.   Our ecommerce platform can be used on any website or CMS (it is embedded using JS). We don't control what JS libraries and code our merchants use on their websites. 
Recently we switched from PayPal Standard integration to the new "checkout.js" based one. Now some our merchants have issues with PayPal -- some JS code on their websites prevent it from working.

Yes, it is clear that the issue is connected to some errors in that 3d-party JS code. However we cannot ask merchants to fix these issues -- they're not developers.

That merchants think that it is PayPal's issue and our platform's issue. They expect PayPal to work on their websites.

We really don't want to switch back to PayPal Standard. So, is there any workaround or solution you can implement to overcome this issue in 3d-party JS libs?

2. The "bind" issue is related to the first example. The second example is different and uses different JS code: http://lamp.ecwid.com/~borman/paypal_2.html

**Comment by qetzal** [comment]
1. Yes, we will try this workaround. I hope it will fix the first issue.

2. However as I understand it will not fix the compatibility with the MooTools library, right? (second example)

**Comment by bluepnume** [comment]
Looks like in the second page it's breaking because `window.Window` is being overwritten by mootools.

Normally:

<img width="299" alt="screen shot 2018-03-09 at 2 26 05 pm" src="https://user-images.githubusercontent.com/1219075/37233003-496da1bc-23a6-11e8-8248-6c6260688e2d.png">

With mootools:

<img width="623" alt="screen shot 2018-03-09 at 2 26 21 pm" src="https://user-images.githubusercontent.com/1219075/37233004-4982f8aa-23a6-11e8-86de-aa949888132c.png">

Quick hack to fix:

```
window.Window = window.constructor;
```
