### ISSUE TITLE
PERMISSION_DENIED errors in Sandbox

### ISSUE THREAD

**Issue by grahamyesfit** [paypal/paypal-checkout#650]
### Description

I have a React JS application and I'm using PayPal checkout to create the payment on the client, and then execute it on the server. I'm importing PayPal functionality from:
https://www.paypalobjects.com/api/checkout.js

I'm using React 15.6.2.

When I try to execute a payment or refund an authorization in my Sandbox, I receive a PERMISSION_DENIED error from my REST call.

The execute payment URL is:
https://api.sandbox.paypal.com/v1/payments/payment/{0}/execute

The response I receive is:
```{"name":"PERMISSION_DENIED","message":"No permission for the requested operation","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"50e26e8fd4444"}```

The call works in Production.

The refund URL is:
https://api.sandbox.paypal.com/v1/payments/capture/{0}/refund

The response I receive is:
```{"name":"PERMISSION_DENIED","message":"Permission denied.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"f06696c091a95"}```

This is new code and I haven't tried it in Production yet, but I suspect the issue has something to do with the way my Sandbox account has been configured.

### Steps to reproduce

1. Create a payment in the client
2. Send the payment information to the server
3. Execute the payment using a REST call
4. OR, refund the payment using a REST call. Both fail in my Sandbox.

### Affected browsers

All browsers.

**Comment by bluepnume** [comment]
@trainerbill can you take a look?

**Comment by trainerbill** [comment]
@grahamyesfit First off you void an authorization not refund.  You only refund a capture.

For the top one with debug_id 50e26e8fd4444, it looks like you are creating a payment against a billing plan.  I did make a permission change on your sandbox account that may help.  

For the bottom one with debug_id f06696c091a95 the transaction id is 60D796004F3681509 and that is showing as a pending authorization because it is iACH.  So you would want to void the authorization not refund which is why you are getting permission denied

If you have additional questions about your integration head over to the gitter chat and I can help you out.  https://gitter.im/paypal/paypal-checkout
