### ISSUE TITLE
Checkout.js is not working whenever trying from website added to home screen (standalone pwa)  on iphone

### ISSUE THREAD

**Issue by ArkeshGKalathiya** [paypal/paypal-checkout#699]
### Description

we have created PWA, and when we are using application from safari (without adding to home screen) it is working fine. But whenever we tried to do payment from icon added to home screen, payment amount is not showing on home page and also after login it is redirecting to dashboard. we also tried putting static amount in js but still not working.

-clue 

we were inspecting pwa from safari, and whenever paypal redirection occurres it closes the inspection window , and it is working fine whenever we are using directly from safari

### Steps to reproduce

create ionic project
and put paypal button
then create browser build 
and use it via Add to homescreen iphone functionality.

### Affected browsers

- [x] Safari
- [x] Safari Mobile/Tablet
- [x] Web View / Safari ViewController
- [x] Other

**Comment by bluepnume** [comment]
Marking this as a feature request; need to research if it's actually even possible to run this component in a PWA. @mcntsh can you do a little research when you have a spare sec and see what the effort would look like and if it's possible?

**Comment by mcntsh** [comment]
This is an interesting issue. When you save a `mobile-web-app-capable` webpage to your iOS homescreen, it will open in its own wrapper app using a WebView, and clicking the PayPal button will open up Safari. Since they are both two separate apps, they have no context of each other and the checkout window won't have access to the button's props.

The way this is handled for _native_ WebViews, is that we detect the environment through the User Agent and then we open up an iFrame rather than a pop-up. The issue in this case is that non-native WebViews are indistinguishable from a mobile Safari browser in the way we do our detection and are treated like a mobile browser. 

I'm going to do some experimenting on how we can detect these non-native WebViews.

**Comment by cpro90** [comment]
@natanaeladit We are facing exactly the same error using paypal checkout from a PWA - ios AND android. It worked fine a couple of weeks ago.

It does not seem there is a fix right now.

**Comment by natanaeladit** [comment]
@cpro90 what is the best way to handle it? should we submit a new issue or?

**Comment by cpro90** [comment]
I removed all access from standalone/PWA to Paypal. Bitter. But I do not see another solution than waiting for official bugfixes yet.

**Comment by KohheePeace** [comment]
@bluepnume @mcntsh Hi, First of all really thank you for your work. I want to notice that this issue is not solved.

My workaround is to change pwa's manifest.json "display" option from "standalone" to "fullscreen"

It is really appreciated if I can use this package with PWA.

Thanks
