### ISSUE TITLE
Missing Documentation for Recurring payments/Billing Agreement

### ISSUE THREAD

**Issue by ajmobidesign** [paypal/paypal-checkout#727]
Hi Guys, 

I have a React app and have successfully implement payment for individual items. The documentation for implementing this was really good.
But now I would like to add a subscription option. There is nothing in the documentation that specifically address this for paypal-checkout.

1. Is this even possible with paypal-checkout? If it is, can you either point me in the direction of documentation for it or can someone post it?

2. If is it is not possible to implement it with paypal-checkout, what do you recommend for implementing it client-side?

thanks

**Comment by vishakha94** [comment]
@ajmobidesign Can you pls specify in detail what kind of subscription need is there?

**Comment by oortega** [comment]
Hi @ajmobidesign The idea is like asking the client if he wants us to charge him the same amount each month, it's possible?

Thanks.

**Comment by ajmobidesign** [comment]
Hi @vishakha94 and @oortega , 
Yes, it is about charging someone a recurring monthly fee.

Probably the best way to show you what I am looking for is to point to the node-SDK version of subscription example.
https://github.com/paypal/PayPal-node-SDK/blob/master/samples/subscription/billing_plans/create.js

Is there a way to do the same with paypal-checkout ? Don't see the documentation for it.

Thanks for taking time to respond.

**Comment by bluepnume** [comment]
@adamlcolson mind if I assign this one your way to triage for the new dev portal?

**Comment by Alir3z4** [comment]
Yes, this is something that I couldn't actually find on the documentation as well.
All the docs are simply playing around with one time payment and nothing is mentioned about BillingAgreement/Subscription/Monthly payments.

Would be great if there's any resources to look into while the documentation is getting ready.

@ajmobidesign were you able to find the solution ?

Also some resources that I've found:

* https://github.com/paypal/paypal-checkout/issues/133
* https://github.com/paypal/paypal-checkout/blob/master/docs/button.md#advanced-integration

**Comment by adamlcolson** [comment]
Hi there @ajmobidesign,

You may want to take a look at the Subscriptions documentation that we just recently released at https://developer.paypal.com/docs/subscriptions/. Part of this solution is supported by checkout.js, but you would still have to do a server-side integration with our REST APIs for creating a billing plan and executing the billing agreement.

Please let me know your thoughts on our Subscriptions documentation, and if this meets your needs.

Thanks,
Adam

**Comment by raRaRa** [comment]
Hi @adamlcolson - where can I find the client-side part of the integration on https://developer.paypal.com/docs/subscriptions/ ?
Is the chekout.js solution identical to payments, e.g. instead of creating a payment I create an agreement, and instead of executing a payment I should execute an agreement?

Because in the client-side solution, I need to specify payment (POST to create payment) and onAuthorize (POST to execute payment)

Thanks!

**Comment by adamlcolson** [comment]
Hi @raRaRa. You will have to create a billing plan, a billing agreement, and then direct your customer to the approval_url in the create agreement response in order to get their approval. The final step is executing the agreement after getting the customer approval. See https://developer.paypal.com/docs/subscriptions/integrate/integrate-steps/#4-get-customer-approval

**Comment by baybird** [comment]
@adamlcolson It seems a lot of ppl seeking the answer of how to get the recurring payment worked with this paypal-checkout package without direct customer to the approval_url.

**Comment by raRaRa** [comment]
I figured this out.

`payment={(data, actions) => this.createAgreement(data, actions)}` 
Instead of creating a payment, I create an agreement in my service.

`onAuthorize={this.onAuthorize}` 
And here I call execute agreement instead of execute payment in my service.

I just wasn't sure if I could use those with recurring payments, but it seems to work just fine.

**Comment by Darkwamba** [comment]
@raRaRa please can you tell me what do you do in this.createAgreement and this.onAuthorize? I have your same need
