### ISSUE TITLE
Capturing amount is pending approval on gateway

### ISSUE THREAD

**Issue by zamoroka** [paypal/paypal-checkout#776]
I've got a message "Capturing amount is pending approval on gateway. Transaction ID: "PAY-xxxxxxx" after  order was placed using PayPal. 
Please describe why this message appears.

The flow on my website:
1. create authorization by calling "/v1/payments/payment" with "intent" = "authorize" 
2. execute authorization "/v1/payments/payment/paymentId/execute"
3. and than capture payment "/v1/payments/authorization/authorizationId/capture"

**Comment by bluepnume** [comment]
@trainerbill are you familiar with this?

**Comment by trainerbill** [comment]
@zamoroka I am guessing that the payment is in review and needs to be accepted by you due to your account settings.  Take a look here:

https://www.sandbox.paypal.com/cgi-bin/customerprofileweb?cmd=_profile-pref

or remove the sandbox if you are in production.  For instance if you have "Allow payments sent to me in a currency I do not hold:" set to ask then its waiting for your review.  there are some other options there as well that will put payments into a review state.

**Comment by zamoroka** [comment]
I'm sorry. Issue is resolved on my side. In some cases `capture` was processed in a moment before `execute authorization`. so it can't be captured
