### ISSUE TITLE
WebView - Field focusing beneath (merchant page) after opening PayPal page in iframe

### ISSUE THREAD

**Issue by venkat-durai** [paypal/paypal-checkout#791]
### Description
The focus of the cursor is still on the parent page ( Merchant website) than switching the focus to PayPal page along once the iframe loaded, which is causing little confusion for the user and experience.

Sample screen:
![iframe-cursor-issue](https://user-images.githubusercontent.com/12368643/44054344-307f3e50-9ef7-11e8-8a20-6aa4d2e3ae76.gif)

### Steps to reproduce

Checkout using PayPal on any webview ( e.g Facebook, Messanger ..)

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [x] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
@mcntsh assigning this to you since it looks like a similar problem to https://github.com/paypal/paypal-checkout/issues/788 -- but with some nuances since we need to keep the focus inside the iframe. Maybe the same solve, maybe not. Or @vishakha94 if you fancy an interesting problem please feel free to take a look. :)

**Comment by mcntsh** [comment]
PR #896 will have addressed this UX concern and the fix will be out in the next release. Thanks for reporting!
