### ISSUE TITLE
PaymentID returned from checkout results in "INVALID_RESOURCE_ID" when used with the REST API to capture/execute a payment

### ISSUE THREAD

**Issue by realfresh** [paypal/paypal-checkout#840]
### Description

Been using PayPal checkout for over one year now. No noticeable issues until recently. Right now my integration uses checkout to initialize the payment and later when the customer's order is confirmed, the payment is executed/captured using the REST API on our server.

However recently, I've had several clients of mine report that their PayPal payments are not being captured. When I took a closer look, the checkout widget is returning the paymentID and payerID but later on when I use that payment ID to capture the payment, I keep getting the error "INVALID_RESOURCE_ID" which means the payment is not found. When I check my client's accounts, the payment is not reported anywhere either. How can the widget be returning me a paymentID only for it to not exist?

Please keep in mind this has only started happening in the last 2 weeks to some clients occasionally. Majority of my customers are not facing this issue. 

Some of my customers are losing $100's because of this issue and its getting quite frustrating as it was working fine for one year and then suddenly has become an issue.

### Steps to reproduce

Unknown

### Affected browsers

Unknown

**Comment by dxeoane** [comment]
I am experiencing a similar problem, I have a series of payments (less than 10%) of which I have the paymentId and the payerId but I can not execute them.

When I try to execute one of those payments, it returns the error PAYMENT_ALREADY_DONE, but when I try to find that payment using REST API I have the error INVALID_RESOURCE_ID. Those two answers are incompatible with each other

None of those payments appear in my Paypal account, so I do not understand where they have gone.

I do not know if it will be relevant, but since a few days ago the paymentId of the payments has gone from starting with "PAY-" to starting with "PAYID-", which leads me to think about some change in the paypal servers.

**Comment by realfresh** [comment]
Any word on this? It's still happening and clients are randomly losing money. Happen's like once in every 50ish payments or something.

**Comment by bluepnume** [comment]
Hi! Can you please share the `paypal-debug-id` header from the response of a failing api call?

**Comment by realfresh** [comment]
Hey, thanks for the response. I'll try, but I have to set up some extra logging to catch it in action. Hopefully, I can get around to it soon 😓
