### ISSUE TITLE
"Buy Now" button does not present a "guest" flow option when cards (funding icons) are enabled.

### ISSUE THREAD

**Issue by bill-z** [paypal/paypal-checkout#920]
I'm using an unbranded "buy now" button with the cards displayed.
(label: 'buynow', fundingicons: true, branding: true)

With past versions, after pressing the "Buy Now" button, the modal presented a choice of paying with an account or a "guest" credit card checkout flow without an account.

With 4.0.229, after selecting "buy now" the modal presents only two options:  sign in, and enter a card to create an account.

Only clicking on a card image presents the modal with a guest option.

Is this new behavior?
If so, was the change intentional?

Steps to reproduce:

navigate to https://developer.paypal.com/demo/checkout/#/pattern/buynow
click "buy now"

**Comment by lucius-pl** [comment]
Experienced the same issue.

**Comment by mcntsh** [comment]
Hey guys, this is intentional. The goal here is to present the buyer with the flow they've intentionally chosen. Clicking a card button will open up guest checkout, and the PayPal button will open member/signup. In layouts where the cards are not displayed, the PayPal button will act as a catch-all and the buyer will be presented the option to checkout as a guest once they're in the Checkout flow.

**Comment by lucius-pl** [comment]
Thank you for clarification. Much appreciated.
